site_name: Test Scheduler Documentation
site_url: https://aoibheannmangan.github.io/test-scheduler/

repo_url: https://github.com/Aoibheannmangan/test-scheduler.git

docs_dir: docs
site_dir: site

nav:
    - Home: index.md
    - About: about.md
    - User Guide:
          - Getting Started: user-guide/getting-started.md
          - Requirements: user-guide/requirements.md
          - License: user-guide/license.md
    - Scheduler Guide:
          - Login: jsdocs/login.md
          - Signup: jsdocs/signup.md
          - Forgot Password: jsdocs/forgotpsw.md
          - Forecast: jsdocs/forecast.md
          - Appointment View: jsdocs/appointview.md
          - Calendar: jsdocs/calendar.md
          - Appointment: jsdocs/appointment.md
    - Components Guide:
          - Alert: jsdocs/alert.md
          - Clickable Cell: jsdocs/clickablecell.md
          - Custom Toolbar: jsdocs/customtoolbar.md
          - Navbar: jsdocs/navbar.md
          - Pop Up: jsdocs/popup.md
          - Rebooking Form: jsdocs/rebooking.md

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - python
        - bash

plugins:
    - mkdocstrings:
          handlers:
              python:
                  paths: ["."]

palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
          icon: material/toggle-switch
          name: Switch to light mode
