site_name: Test Scheduler Documentation
site_url: https://aoibheannmangan.github.io/test-scheduler/

repo_url: https://github.com/Aoibheannmangan/test-scheduler.git

docs_dir: docs
site_dir: site

nav:
    - Home: index.md
    - About: about.md
    - User Guide:
          - Requirements: user-guide/requirements.md
          - License: user-guide/license.md
    - Scheduler Guide:
          - Login: jsdocs/login.md
          - Signup: jsdocs/signup.md
          - Forgot Password: jsdocs/forgotpsw.md
          - Forecast: jsdocs/forecast.md
          - Appointment View: jsdocs/appointview.md
          - Calendar: jsdocs/calendar.md
          - Appointment: jsdocs/appointment.md
    - Components Guide:
          - Alert: jsdocs/alert.md
          - Clickable Cell: jsdocs/clickablecell.md
          - Custom Toolbar: jsdocs/customtoolbar.md
          - Navbar: jsdocs/navbar.md
          - Pop Up: jsdocs/popup.md
          - Rebooking Form: jsdocs/rebooking.md
    - API Documentation: 
          - Entry Point: jsdocs/entrypoint.md
          - Routes: 
            - Overview: jsdocs/routes.md
            - Appointment: jsdocs/appointmentRoutes.md
            - Blocked: jsdocs/blockedRoutes.md
          - Helper Functions: jsdocs/helpers.md 

theme:
    name: material
    palette:
        # Palette toggle for light mode
        - scheme: default
          primary: blue
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

        # Palette toggle for dark mode
        - scheme: slate
          primary: indigo
          toggle:
              icon: material/brightness-4
              name: Switch to light mode

plugins:
    - search # Added search plugin
    - mkdocstrings:
          default_handler: python
          handlers:
              python:
                  paths: ["."]
                  options:
                      docstring_style: google
                      show_root_full_path: false
